image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  # запускаем SUT (запоминаем информацию о процессе в переменной $App)
  - java -jar ./artifacts/app-order.jar

build_script:
  - ps:  chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме (см.ниже)

